# config.yaml
# --- Paths ---
base_data_dir: /Volumes/EasyStore/RAWNIND/
jpeg_output_subdir: /Volumes/EasyStore/RAWNIND/JPEGs/Cropped_JPEG
cropped_jpeg_subdir: /Volumes/EasyStore/RAWNIND/JPEGs/Cropped_JPEG
align_csv: align_data.csv
secondary_align_csv: align_phase_v2.csv
script_path: traces_and_weights
mlflow_path: /Volumes/EasyStore/models/mlfow

# --- Training Params ---
colorspace: lin_rec2020
device: mps
batch_size: 2
crop_size: 256
lr_base: 2.5e-5 
clipping: 1e-2
num_epochs_pretraining: 50
num_epochs_finetuning: 20
val_split: 0.2
random_seed: 42

# --- Experiment Settings ---
experiment: NAF_test
mlflow_experiment: NAFNet_variations

# --- Run Configuration ---:
run_name: NAF_deep_test_align
run_path: NAF_deep_test_align
model_params:
  chans: [32, 64, 128, 256, 256, 256]
  enc_blk_nums: [2, 2, 2, 3, 4]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2, 2]
  cond_input: 1
  in_channels: 4
  out_channels: 3
  rggb: True

# --- Loss Configureation ---:
alpha: 0.2
beta: 5.0
l1_weight: 0.16
ssim_weight: 0.84
tv_weight: 0.0
vgg_loss_weight: 0