# config.yaml
# --- Paths ---
cropped_raw_subdir: Cropped_Raw/
cropped_raw_size: 2000
secondary_align_csv: align_phase_v2_exposure_corr.csv
script_path: /content/drive/MyDrive/OnSight/traces
mlflow_path: /content/drive/MyDrive/OnSight/mlflow

# --- Training Params ---
colorspace: lin_rec2020
device: mps
batch_size: 2
crop_size: 256
lr_base: 2.5e-5 
clipping: 1e-2
num_epochs_pretraining: 270
num_epochs_finetuning: 100
val_split: 0.2
random_seed: 42
cosine_annealing: True
iso_range: [0, 999999]

# --- Experiment Settings ---
experiment: NAF_test
mlflow_experiment: NAFNet_variations

# --- Run Configuration ---:
run_name: NAF_debayer_in_add_connections
run_path: NAF_deep_test_align
model_params:
  # chans: [64, 128, 256, 512, 512, 512]
  chans: [32, 64, 128, 256, 256, 256]

  enc_blk_nums: [2, 2, 2, 3, 4]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2, 2]
  cond_input: 1
  in_channels: 3
  out_channels: 3
  rggb: False
  use_CondFuserV2: False
  use_add: True
  use_CondFuserV3: False
  use_attnblock: False
  use_CondFuserV4: False
  use_NAFBlock0_learned_norm: False
  use_input_stats: False
  gamma: 2.2

# --- Loss Configureation ---:
# alpha: 0.2
# beta: 5.0
# l1_weight: 0.16
# ssim_weight: 0.84
# tv_weight: 0.0
# vgg_loss_weight: 0.0
# percept_loss_weight: 0.025

dist_w: 0
l1_w: 1
msssim_w: 0
alpha_beta_gamma: [1,1,1]