# config.yaml
# --- Paths ---
# base_data_dir: /Volumes/EasyStore/RAWNIND/
# jpeg_output_subdir: /Volumes/EasyStore/RAWNIND/JPEGs/Cropped_JPEG
# cropped_jpeg_subdir: /Volumes/EasyStore/RAWNIND/JPEGs/Cropped_JPEG
cropped_raw_subdir: /Users/ryanmueller/Develop/Cropped_Raw/
cropped_raw_size: 2000
align_csv: align_data.csv
secondary_align_csv: align_phase_v2.csv
script_path: /Users/ryanmueller/Develop/traces/
mlflow_path: /Users/ryanmueller/Develop/mlflow/

# --- Training Params ---
colorspace: lin_rec2020
device: mps
batch_size: 2
crop_size: 256
lr_base: 2.5e-5 
clipping: 1e-2
num_epochs_pretraining: 5
num_epochs_finetuning: 20
val_split: 0.2
random_seed: 42
cosine_annealing: False
iso_range: [0, 999999]

# --- Experiment Settings ---
experiment: Demosaicing
mlflow_experiment: Demosaicing

# --- Run Configuration ---:
run_name: Demosaicing_test_5x5_just_l1
run_path: Demosaicing_Test
model_params:
  chans: [12, 24]
  enc_blk_nums: [1]
  middle_blk_num: 1
  dec_blk_nums: [1]
  cond_input: 1
  in_channels: 4
  out_channels: 3
  rggb: True
  use_CondFuserV2: False
  use_add: False
  use_CondFuserV3: False
  use_attnblock: False
  use_CondFuserV4: False
  use_NAFBlock0_learned_norm: False
  use_input_stats: False
  gamma: 1.0

# --- Loss Configureation ---:
alpha: 1.0
beta: 5.0
l1_weight: 1
ssim_weight: 0
tv_weight: 0.0
vgg_loss_weight: 0.0
percept_loss_weight: 0.0